### ISSUE TITLE
erreur connection refused

### ISSUE THREAD

**Issue by pwepwe973** [music-library/music-library#1]
bonjour je rencontre un problème connexion refusé

the log 

index.js:17 Music Library [Version 2.1.0]
polling-xhr.js:268 GET http://localhost:7789/socket.io/?EIO=3&transport=polling&t=NOP8fR_ net::ERR_CONNECTION_REFUSED
c.create @ polling-xhr.js:268
c @ polling-xhr.js:170
h.request @ polling-xhr.js:96
h.doPoll @ polling-xhr.js:126
h.poll @ polling.js:118
h.doOpen @ polling.js:63
a.open @ transport.js:84
h.open @ socket.js:250
h @ socket.js:122
h @ socket.js:28
d.open.d.connect @ manager.js:226
d @ manager.js:69
d @ manager.js:37
u @ index.js:60
343 @ reducer.js:60
l @ tracks:1
187 @ main.19bcb159.chunk.js:1
l @ tracks:1
t @ tracks:1
r @ tracks:1
(anonymous) @ main.19bcb159.chunk.js:1
localhost:7789/tracks/example/cover/400:1 GET http://localhost:7789/tracks/example/cover/400 net::ERR_CONNECTION_REFUSED
Image (async)
$ @ react-dom.production.min.js:28
Jo @ react-dom.production.min.js:201
hu @ react-dom.production.min.js:247
lu @ react-dom.production.min.js:246
su @ react-dom.production.min.js:246
Qs @ react-dom.production.min.js:239
Ys @ react-dom.production.min.js:230
Du @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
tu @ react-dom.production.min.js:240
Gu @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
343 @ index.js:44
l @ tracks:1
187 @ main.19bcb159.chunk.js:1
l @ tracks:1
t @ tracks:1
r @ tracks:1
(anonymous) @ main.19bcb159.chunk.js:1
xhr.js:178 GET http://localhost:7789/tracks net::ERR_CONNECTION_REFUSED
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:50
Promise.then (async)
u.request @ Axios.js:61
r.forEach.u.<computed> @ Axios.js:76
(anonymous) @ bind.js:9
(anonymous) @ actionCreators.js:31
(anonymous) @ index.js:8
(anonymous) @ App.js:30
is @ react-dom.production.min.js:211
gu @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Gi @ react-dom.production.min.js:122
mu @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
F @ scheduler.production.min.js:17
S.port1.onmessage @ scheduler.production.min.js:14

**Comment by hmerritt** [comment]
This is happening because the `backend` is not running and the client can't connect to it.

If you are using docker (highly recommended) then a simple `docker-compose` is all that's needed;

> `path-to-your-music` - replace this with the directory of your music: `/home/myuser/music`
> `path-to-caching-dir` - this volume is used to store data for the music-library: `/home/myuser/music-library`

```yaml
version: "3"

services:
  
  music-player:
    image: hmerritt/music-library-player:latest
    #build: .

    environment:
        - REACT_APP_HTTP=http
        - REACT_APP_HOST=localhost:7788
        - REACT_APP_API=http://localhost:7789
        - REACT_APP_BUGCATCH_ENABLE=false
        - BUGCATCH_MONGO_URI=""
        - DEBUG=

    ports:
      - 7788:80
      - 7789:8000

    volumes:
      - path-to-your-music:/app/music
      - path-to-caching-dir:/app/data
```

> If you already are using docker then my guess is the backend crashed because you entered the `volumes` path incorrectly.
