### ISSUE TITLE
Music is not displaying and all is empty

### ISSUE THREAD

**Issue by nesticle8bit** [music-library/music-library#3]
![image](https://github.com/music-library/music-library/assets/1715022/a8220ce3-8b9a-456b-a5cb-342f990b0fbb)

Hello everyone!, recently I installed the docker music-library using this docker-compose:

```
version: "3"
services:
  music-player:
    image: hmerritt/music-library-player:latest
    container_name: music-library
    environment:
        # Client
        - REACT_APP_HTTP=http
        - REACT_APP_HOST=localhost:7788
        - REACT_APP_API=localhost:7789
        # Server
        - MUSIC_DIR_NAME=Music
    ports:
      - 7788:80
      - 7789:8000
    restart: unless-stopped
    volumes:
      - /home/myuser/Documents/dev/docker/music-library/cache:/app/data
      - /mnt/Music:/app/music
```

All my music catalog is in **/mnt/Music** and the folder that contains the music is in the folder **Music** , but im not getting any kind of music, playlists, artists, nothing, what Im doing wrong?
